import { ScreenerResult, StockAnalysis } from './types';

// Mock screener results
export const mockScreenerResults: ScreenerResult[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Technology',
    industry: 'Consumer Electronics',
    price: 150.25,
    change: 2.15,
    changePercent: 1.45,
    marketCap: 2400000000000,
    volume: 45200000,
    score: 87,
    overall_score: 87,
    sector_pe_benchmark: 25.2,
    sector_relative_score: 85,
    top_drivers: ['Strong ecosystem', 'Growing services revenue', 'Robust cash flow'],
    sector_analysis: 'Technology sector leader with premium valuation justified by growth',
    data_source: 'finviz+yfinance',
    last_updated: new Date().toISOString(),
    pe_ratio: 24.5,
    pb_ratio: 7.2,
    dividend_yield: 0.6,
    revenue_growth: 8.5,
    rationale: 'Strong ecosystem, growing services revenue, robust cash flow generation',
    style_scores: {
      buffett: 85,
      lynch: 78,
      momentum: 82,
      deep_value: 45,
      dividend: 62,
    },
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'Technology',
    industry: 'Internet Content & Information',
    price: 2850.50,
    change: 22.75,
    changePercent: 0.81,
    marketCap: 1800000000000,
    volume: 18500000,
    score: 82,
    overall_score: 82,
    sector_pe_benchmark: 25.2,
    sector_relative_score: 78,
    top_drivers: ['Dominant search position', 'Strong AI capabilities', 'Cloud growth'],
    sector_analysis: 'Technology giant with AI leadership and cloud expansion',
    data_source: 'finviz+yfinance',
    last_updated: new Date().toISOString(),
    pe_ratio: 22.1,
    pb_ratio: 5.8,
    dividend_yield: 0.0,
    revenue_growth: 12.3,
    rationale: 'Dominant search market position, strong AI capabilities, cloud growth',
    style_scores: {
      buffett: 88,
      lynch: 85,
      momentum: 75,
      deep_value: 52,
      dividend: 0,
    },
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    sector: 'Technology',
    industry: 'Software Infrastructure',
    price: 420.15,
    change: 8.65,
    changePercent: 2.1,
    marketCap: 3100000000000,
    volume: 22100000,
    score: 89,
    overall_score: 89,
    sector_pe_benchmark: 25.2,
    sector_relative_score: 92,
    top_drivers: ['Azure cloud dominance', 'Office 365 growth', 'AI integration'],
    sector_analysis: 'Software infrastructure leader with cloud and AI advantages',
    data_source: 'finviz+yfinance',
    last_updated: new Date().toISOString(),
    pe_ratio: 28.3,
    pb_ratio: 11.2,
    dividend_yield: 0.8,
    revenue_growth: 15.7,
    rationale: 'Azure cloud dominance, Office 365 growth, AI integration across products',
    style_scores: {
      buffett: 92,
      lynch: 88,
      momentum: 90,
      deep_value: 38,
      dividend: 68,
    },
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'Technology',
    industry: 'Semiconductors',
    price: 875.50,
    change: 27.25,
    changePercent: 3.21,
    marketCap: 2150000000000,
    volume: 38900000,
    score: 91,
    overall_score: 91,
    sector_pe_benchmark: 25.2,
    sector_relative_score: 95,
    top_drivers: ['AI chip leadership', 'Data center growth', 'Gaming GPU dominance'],
    sector_analysis: 'Semiconductor leader with AI and gaming market dominance',
    data_source: 'finviz+yfinance',
    last_updated: new Date().toISOString(),
    pe_ratio: 65.2,
    pb_ratio: 48.5,
    dividend_yield: 0.04,
    revenue_growth: 126.5,
    rationale: 'AI chip leadership, data center growth, gaming GPU dominance',
    style_scores: {
      buffett: 45,
      lynch: 95,
      momentum: 98,
      deep_value: 12,
      dividend: 15,
    },
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'Consumer Cyclical',
    industry: 'Internet Retail',
    price: 3250.75,
    change: 54.20,
    changePercent: 1.70,
    marketCap: 3350000000000,
    volume: 28700000,
    score: 78,
    overall_score: 78,
    sector_pe_benchmark: 18.5,
    sector_relative_score: 72,
    top_drivers: ['AWS market leader', 'E-commerce scale', 'Advertising growth'],
    sector_analysis: 'Consumer cyclical leader with cloud and retail dominance',
    data_source: 'finviz+yfinance',
    last_updated: new Date().toISOString(),
    pe_ratio: 72.8,
    pb_ratio: 8.1,
    dividend_yield: 0.0,
    revenue_growth: 11.2,
    rationale: 'AWS market leader, e-commerce scale, advertising growth',
    style_scores: {
      buffett: 62,
      lynch: 82,
      momentum: 78,
      deep_value: 25,
      dividend: 0,
    },
  },
];

// Mock detailed stock analysis
export const mockStockAnalysis: StockAnalysis = {
  symbol: 'AAPL',
  name: 'Apple Inc.',
  sector: 'Technology',
  price: 150.25,
  marketCap: 2400000000000,
  overview: {
    summary: 'Apple shows strong fundamentals with robust cash flow generation and expanding services revenue. Technical indicators suggest bullish momentum with RSI at 65. DCF analysis indicates 15% upside potential. The company benefits from a strong ecosystem lock-in and growing services segment.',
    bullPoints: [
      'Services revenue growing at 20%+ annually',
      'Strong brand loyalty and ecosystem lock-in',
      'Expanding into new product categories (Vision Pro, AI)',
      'Massive cash reserves for buybacks and dividends',
      'Leading position in premium smartphone market',
    ],
    bearPoints: [
      'High exposure to China market (regulatory risks)',
      'iPhone revenue growth slowing',
      'Intense competition in services',
      'Valuation concerns at current multiples',
      'Dependency on iPhone for majority of revenue',
    ],
    keyRisks: [
      'Regulatory risk in multiple jurisdictions',
      'Market saturation in developed countries',
      'Supply chain vulnerabilities',
      'Competition from Android ecosystem',
    ],
    catalysts: [
      { event: 'AI features in iOS 18', date: '2025-06-15', impact: 'high' },
      { event: 'Vision Pro international launch', date: '2025-Q2', impact: 'medium' },
      { event: 'Services bundling expansion', impact: 'medium' },
      { event: 'Next earnings report', date: '2025-01-30', impact: 'high' },
    ],
    week52High: 198.23,
    week52Low: 124.17,
    volume: 45200000,
    avgVolume: 52300000,
  },
  fundamentals: {
    pe_ratio: 24.5,
    pb_ratio: 7.2,
    ps_ratio: 6.8,
    roe: 18.2,
    roa: 12.1,
    debt_to_equity: 0.15,
    current_ratio: 1.8,
    gross_margin: 45.2,
    revenue_growth: 8.5,
    earnings_growth: 12.3,
    dividend_yield: 0.6,
  },
  technical: {
    trend: {
      short_term: 'bullish',
      medium_term: 'bullish',
      long_term: 'bullish',
      strength: 0.78,
    },
    indicators: {
      rsi: { value: 65, signal: 'Bullish', overbought: false, oversold: false },
      macd: { macd_line: 2.15, signal_line: 1.85, histogram: 0.30, signal: 'Bullish' },
      sma_20: 148.50,
      sma_50: 145.20,
      sma_200: 142.80,
    },
    support_levels: [145.50, 142.20, 138.00],
    resistance_levels: [155.80, 162.50, 170.00],
    technical_score: 75,
    technical_rating: 'bullish',
  },
  dcf: {
    fair_value: 172.50,
    current_price: 150.25,
    upside_downside: 14.8,
    confidence_level: 0.85,
    wacc: 8.5,
    scenarios: {
      bull: { price: 195.00, probability: 0.25 },
      base: { price: 172.50, probability: 0.50 },
      bear: { price: 125.00, probability: 0.25 },
    },
    key_drivers: [
      'Services revenue growth acceleration',
      'Margin expansion from product mix',
      'Share buyback program continuation',
      'New product category adoption (Vision Pro)',
    ],
    key_risks: [
      'iPhone sales decline',
      'China regulatory issues',
      'Competitive pressure in services',
      'Economic slowdown impact on premium devices',
    ],
  },
  dca: {
    recommended_strategy: 'ATR-Weighted DCA',
    frequency: 'Weekly',
    entry_price_range: { low: 145.00, high: 150.00 },
    strategies: [
      { name: 'Fixed Amount', total_return: 12.5, sharpe_ratio: 1.2, max_drawdown: -8.2, win_rate: 0.68 },
      { name: 'ATR-Weighted', total_return: 15.3, sharpe_ratio: 1.4, max_drawdown: -6.1, win_rate: 0.72 },
      { name: 'Drawdown-Based', total_return: 14.1, sharpe_ratio: 1.3, max_drawdown: -7.3, win_rate: 0.70 },
      { name: 'Fibonacci', total_return: 13.8, sharpe_ratio: 1.3, max_drawdown: -6.8, win_rate: 0.69 },
      { name: 'Lump Sum', total_return: 11.2, sharpe_ratio: 1.1, max_drawdown: -12.5, win_rate: 0.65 },
      { name: 'Buy and Hold', total_return: 10.8, sharpe_ratio: 1.0, max_drawdown: -15.2, win_rate: 0.63 },
    ],
    risk_level: 'medium',
    position_size_recommendation: '5-8% of portfolio',
  },
};

